# AniCat setting toggles (also update the real Anicat app setting)
# ctrl+1 -> Toggle upscaling on/off
# ctrl+2 -> Toggle auto-skip intro on/off

# AniCat playback controls
# R -> Reload Episode
# A -> Toggle Auto-play
# T -> Toggle Dub / Sub
# S -> Skip Intro / Active Skip Segment

# --- Setting toggles ---
ctrl+1 script-message anicat-toggle-shaders
ctrl+2 script-message anicat-toggle-autoskip

# --- AniCat playback actions ---
R script-message anicat-reload-episode
A script-message anicat-toggle-auto-next
T script-message anicat-toggle-translation
S script-message anicat-skip-intro


