# Video Quality & GPU Optimizations
vo=gpu
gpu-api=vulkan
profile=high-quality
hwdec=auto-safe

# Persistent GPU Shader Caching (Resolves compile delays on Silicon Mac)
gpu-shader-cache=yes
gpu-shader-cache-dir="~~/shader_cache"

# Complete Borderless Minimalism
border=no
osc=no

# Subtitles styling
sub-auto=fuzzy
sub-font="Outfit"
sub-font-size=44
sub-bold=yes

# Disable the native volume bar overlap
osd-bar=no


