ANINEKO_DOMAIN = "anineko.to"
ANINEKO_BASE_URL = f"https://{ANINEKO_DOMAIN}"

SEARCH_URL = f"{ANINEKO_BASE_URL}/browser"
WATCH_URL = f"{ANINEKO_BASE_URL}/watch"

AJAX_REFERER_HEADER = f"{ANINEKO_BASE_URL}/"
