// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "AnicatApple",
    platforms: [
        .macOS(.v15),
        .iOS(.v18),
        // Apple TV. Same package, same engine; the TV-shaped root lives in
        // `Views/TV*.swift` behind `#if os(tvOS)` and the app target is
        // `AnicatTV` in project.yml. 18 to match iOS: both ship the same
        // SwiftUI generation, and the focus APIs the TV root leans on
        // (`focusSection`, `onMoveCommand`, the `.card` button style) have
        // been there far longer.
        .tvOS(.v18)
    ],
    products: [
        .executable(
            name: "Anicat",
            targets: ["Anicat"]
        ),
        .library(
            name: "AnicatCoreKit",
            targets: ["AnicatCoreKit"]
        ),
        .library(
            name: "AnicatUI",
            targets: ["AnicatUI"]
        )
    ],
    dependencies: [
        // libmpv, FFmpeg and their dependency closure as prebuilt
        // xcframeworks for macOS, iOS, tvOS and visionOS, built with
        // gpu-next, libplacebo and MoltenVK, plus MPVKit's `moltenvk`
        // context patch: mpv draws into a CAMetalLayer we hand it as `wid`.
        // Replaces the Homebrew libmpv this package linked from
        // /opt/homebrew/opt/mpv/lib, which could never work for iOS and
        // tied the macOS build to whatever `brew upgrade` last installed.
        // GPL variant: Anicat is GPL-3 already; the variant adds only
        // Samba, which we do not use, but it is the honest match.
        .package(url: "https://github.com/mpvkit/MPVKit.git", exact: "1.0.0")
    ],
    targets: [
        .binaryTarget(
            name: "AnicatCore",
            path: "Frameworks/AnicatCore.xcframework"
        ),
        .target(
            name: "AnicatCoreKit",
            dependencies: ["AnicatCore"],
            path: "Sources/AnicatCoreKit",
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        ),
        .target(
            name: "AnicatUI",
            dependencies: [
                "AnicatCoreKit",
                .product(name: "MPVKit-GPL", package: "MPVKit")
            ],
            path: "Sources/AnicatUI",
            // The iPhone app icon: project.yml compiles it, and SwiftPM warned
            // on every build that it did not know what to do with it.
            exclude: ["Resources/AppIcon.xcassets"],
            resources: [
                .copy("Resources/Shaders"),
                .process("Resources/Images"),
                .copy("Resources/Fonts"),
                // THIRD_PARTY_NOTICES.txt, generated by
                // scripts/generate-third-party-notices.py. Copied, not
                // processed: it has to reach the bundle byte for byte.
                .copy("Resources/Legal")
            ]
        ),
        .executableTarget(
            name: "Anicat",
            dependencies: ["AnicatUI", "AnicatCoreKit"],
            path: "Sources/AnicatApp"
        ),
        // Covers the FFI boundary itself, independently of any view: the
        // engine constructs, an async Rust future completes on the Swift
        // side, a record round-trips through SQLite, and a Rust Err arrives
        // as a Swift throw.
        .testTarget(
            name: "AnicatCoreKitTests",
            dependencies: ["AnicatCoreKit"],
            path: "Tests/AnicatCoreKitTests"
        ),
        .testTarget(
            name: "AnicatUITests",
            dependencies: ["AnicatUI", "AnicatCoreKit"],
            path: "Tests/AnicatUITests"
        )
    ]
)
