name: Build Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - platform: macos-14
            args: --target aarch64-apple-darwin
            triple: aarch64-apple-darwin
            sidecar_suffix: ''
          - platform: windows-latest
            args: --target x86_64-pc-windows-msvc
            triple: x86_64-pc-windows-msvc
            sidecar_suffix: '.exe'
    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.target.platform }}
      args: ${{ matrix.target.args }}
      triple: ${{ matrix.target.triple }}
      sidecar_suffix: ${{ matrix.target.sidecar_suffix }}
